import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { HelpCircle, Quote } from "lucide-react";
const QUOTE_URL = "https://app.quotemyfence.com.au/#/step/1";
const JunctionVillageFAQSection = () => {
  const handleQuoteClick = () => { window.location.href = QUOTE_URL; };
  const faqs = [{question:"How much does fencing installation cost in Junction Village?",answer:"Junction Village fencing costs depend on the material, height, total length, and site conditions. Timber starts from $65/m, Colorbond from $75/m, pool fencing from $60/m."},{question:"How long does it take to install a fence in Junction Village?",answer:"A standard residential fence (20–30m) usually takes 1–2 days. Larger jobs may take 3–7 days."},{question:"Do I need council approval for my fence in Junction Village?",answer:"Most residential fences under 2 metres don't require council approval, but rules can vary."},{question:"What's the best fencing material for my property in Junction Village?",answer:"Colorbond is durable and low-maintenance. Timber offers natural warmth. Aluminium provides modern style."},{question:"Are the fencing contractors in Junction Village verified and insured?",answer:"Yes. Every contractor on our platform is fully licensed, insured, and professionally vetted."},{question:"How many quotes will I receive?",answer:"You'll receive up to 3 competitive quotes from reputable Junction Village fencing experts within hours."},{question:"Can you repair or replace an existing fence in Junction Village?",answer:"Absolutely. Our contractors handle both repairs and complete fence replacements."},{question:"What happens after I submit my quote request?",answer:"Within minutes, we'll match you with up to 3 qualified local fencing professionals in Junction Village."},{question:"How long will my fence last in Junction Village?",answer:"Colorbond and aluminium fences can last 20–30 years. Timber generally lasts 10–20 years with proper care."},{question:"What factors can increase the total cost of a fence?",answer:"Site preparation, sloped ground, old fence removal, retaining requirements, custom designs, and extra gates."},{question:"Do I need my neighbour's approval for a new boundary fence in Junction Village?",answer:"Yes — boundary fences require both parties to agree on height, materials, and cost sharing."},{question:"How close to the boundary can I build my fence in Junction Village?",answer:"Most boundary fences are installed directly on the shared property line."},{question:"How do I choose the right fence for my home in Junction Village?",answer:"Consider your home's style, privacy needs, and budget. Our contractors can advise during consultation."},{question:"Can a new fence add value to my property?",answer:"Yes. A quality fence improves street appeal, privacy, and security — all adding real value."}];
  return <section className="py-20 bg-gradient-to-b from-background to-secondary/30"><div className="container mx-auto px-4 max-w-4xl"><div className="text-center mb-12 animate-fade-in"><div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-accent/10 mb-6"><HelpCircle className="w-8 h-8 text-accent"/></div><h2 className="text-4xl md:text-5xl leading-[1.15] font-bold mb-4 bg-gradient-to-r from-primary to-primary/70 bg-clip-text text-transparent">Frequently Asked Questions</h2><p className="text-lg text-muted-foreground max-w-2xl mx-auto">Got questions about fencing in Junction Village? We've got answers.</p></div><div className="bg-card rounded-2xl shadow-strong p-6 md:p-8 border border-border/50"><Accordion type="single" collapsible className="space-y-4">{faqs.map((faq,index)=><AccordionItem key={index} value={`item-${index}`} className="border border-border rounded-xl px-6 py-2 bg-card-gradient transition-all duration-300 hover:shadow-soft hover:border-accent/20"><AccordionTrigger className="text-left hover:no-underline group"><div className="flex items-start gap-4 pr-4"><div className="flex-shrink-0 w-8 h-8 rounded-full bg-accent/10 flex items-center justify-center mt-1 group-hover:bg-accent/20 transition-colors"><span className="text-accent font-bold text-sm">{index+1}</span></div><span className="text-base md:text-lg font-semibold text-foreground group-hover:text-accent transition-colors">{faq.question}</span></div></AccordionTrigger><AccordionContent className="text-muted-foreground pl-12 pr-4 pb-4 leading-relaxed">{faq.answer}</AccordionContent></AccordionItem>)}</Accordion></div><div className="text-center mt-12 p-8 rounded-2xl bg-gradient-to-r from-primary/5 via-accent/5 to-primary/5 border border-accent/20"><h3 className="text-2xl font-bold mb-3 text-foreground">Still have questions?</h3><p className="text-muted-foreground mb-6">Our local fencing experts in Junction Village are here to help.</p><Button variant="hero" size="lg" onClick={handleQuoteClick} className="mb-6"><Quote className="w-5 h-5"/>Get Your 3 Free Quotes Now</Button><div className="flex items-center justify-center gap-2 text-sm text-muted-foreground"><span className="text-accent font-bold text-lg">⭐ 4.78</span><span>rating</span><span className="text-border">•</span><span>10,000+ Fences Quoted</span></div></div></div></section>;
};
export default JunctionVillageFAQSection;
