import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { MapPin, Users, Star, Clock, Phone, ChevronDown, ChevronUp } from "lucide-react";
import SuburbLink from "@/components/SuburbLink";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";

const QUOTE_URL = "https://app.quotemyfence.com.au/#/step/1";
const Darwin = () => {
  useDocumentTitle("Darwin Fencing Quotes — Get 3 Free Quotes in Minutes");
  const [showAllSuburbs, setShowAllSuburbs] = useState(false);
  const handleQuoteClick = () => { window.location.href = QUOTE_URL; };
  const suburbs = ["Coconut Grove", "Jingili", "Millner", "Moil", "Nightcliff", "Rapid Creek", "Bayview", "Charles Darwin", "Darwin", "Eaton", "East Point", "Fannie Bay", "Hidden Valley", "Larrakeyah", "Ludmilla", "Parap", "Stuart Park", "The Gardens", "The Narrows", "Winnellie", "Woolner", "Alawa", "Brinkin", "Buffalo Creek", "Casuarina", "Holmes", "Leanyer", "Lee Point", "Lyons", "Muirhead", "Nakara", "Tiwi"];
  const allSuburbs = ["Wagaman", "Wanguri", "Anula", "Berrimah", "Coonawarra", "Karama", "Malak", "Marrara", "Sanderson", "Wulagi", "Bakewell", "Bellamack", "Driver", "Durack", "Gray", "Gunn", "Moulden", "Palmerston City", "Rosebery", "Woodroffe", "Archer", "Farrar", "Johnston", "Marlow Lagoon", "Mitchell", "Pinelands", "Yarrawonga", "Zuccoli", "Bees Creek", "Coolalinga", "Freds Pass", "Girraween", "Holtze", "Howard Springs", "Humpty Doo", "Knuckey Lagoon", "McMinns Lagoon", "Noonamah", "Robertson Barracks", "Virginia", "Berry Springs", "Blackmore", "Channel Island", "Darwin River", "Fly Creek", "Livingstone", "Southport", "Tumbling Waters", "Weddell", "Wickham", "Acacia Hills", "Black Jungle", "Gunn Point", "Herbert", "Hughes", "Lambells Lagoon", "Lloyd Creek", "Manton", "Middle Point", "Murrumujuk", "Wagait Beach", "Mandorah"];
  const stats = [{ icon: Users, label: "Jobs Quoted", value: "600+" }, { icon: Star, label: "Average Rating", value: "4.9/5" }, { icon: Clock, label: "Years Experience", value: "10+" }, { icon: MapPin, label: "Suburbs Serviced", value: "90+" }];
  const recentProjects = [{ suburb: "Fannie Bay", type: "Colorbond Fence", rating: 5, review: "Everything was handled efficiently and with care. The crew arrived as promised and delivered a fence that looks outstanding." }, { suburb: "Parap", type: "Timber Fence", rating: 5, review: "Impressive build quality paired with sensible pricing. A team I'd confidently recommend." }, { suburb: "Stuart Park", type: "Timber Fence", rating: 5, review: "The outcome went well beyond what we anticipated. The fence is beautifully finished and the service was exceptional throughout." }];
  return <div className="min-h-screen bg-background">
      <Header onQuoteClick={handleQuoteClick} />
      <section className="relative pt-32 pb-20 overflow-hidden"><div className="absolute inset-0 accent-gradient opacity-10"></div><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><div className="text-center max-w-4xl mx-auto"><div className="inline-flex items-center space-x-2 bg-primary/10 px-4 py-2 rounded-full mb-6"><MapPin className="w-4 h-4 text-primary" /><span className="text-sm font-medium text-primary">Servicing All Darwin Suburbs</span></div><h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">Darwin's Most Trusted<br /><span className="text-gradient">Fencing Specialists</span></h1><p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">Professional fencing installation and repair services across Greater Darwin. Local tradies, trusted by 600+ Darwin homeowners.</p><div className="flex flex-wrap gap-4 justify-center"><Button variant="quote" size="lg" onClick={handleQuoteClick}>Get Free Darwin Quotes</Button><Button variant="outline" size="lg" asChild><a href="tel:0481752344" aria-label="Call 0481 752 344"><Phone className="w-4 h-4 mr-2" />Call 0481 752 344</a></Button></div></div></div></section>
      <section className="py-12 bg-muted/30"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-2 lg:grid-cols-4 gap-6">{stats.map((stat, index) => <Card key={index} className="text-center border-border/50"><CardContent className="p-6"><div className="w-12 h-12 accent-gradient rounded-full flex items-center justify-center mx-auto mb-3"><stat.icon className="w-6 h-6 text-white" /></div><div className="text-3xl font-bold text-foreground mb-1">{stat.value}</div><div className="text-sm text-muted-foreground">{stat.label}</div></CardContent></Card>)}</div></div></section>
      <section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">We Service All Darwin Suburbs</h2><p className="text-lg text-muted-foreground max-w-2xl mx-auto">From Palmerston to Nightcliff, we've got Darwin covered</p></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8">{suburbs.map((suburb, index) => <SuburbLink key={index} suburb={suburb} cityPath="/darwin" />)}</div>{showAllSuburbs && <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8">{allSuburbs.map((suburb, index) => <SuburbLink key={index} suburb={suburb} cityPath="/darwin" />)}</div>}<div className="text-center"><p className="text-muted-foreground mb-4">Don't see your suburb? We service the entire Greater Darwin area!</p><Button variant="outline" onClick={() => setShowAllSuburbs(!showAllSuburbs)}>{showAllSuburbs ? <><ChevronUp className="w-4 h-4 mr-2" />Hide Suburbs</> : <><ChevronDown className="w-4 h-4 mr-2" />View All Suburbs</>}</Button></div></div></section>
      <section className="py-20 bg-muted/30"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Recent Darwin Projects</h2><p className="text-lg text-muted-foreground max-w-2xl mx-auto">See what your neighbours are saying about their fencing projects</p></div><div className="grid md:grid-cols-3 gap-6">{recentProjects.map((project, index) => <Card key={index} className="hover-scale border-border/50"><CardContent className="p-6"><div className="flex items-center justify-between mb-4"><div className="flex items-center space-x-2"><MapPin className="w-4 h-4 text-primary" /><span className="font-semibold text-foreground">{project.suburb}</span></div><div className="flex items-center space-x-1">{[...Array(project.rating)].map((_, i) => <Star key={i} className="w-4 h-4 fill-primary text-primary" />)}</div></div><p className="text-sm text-muted-foreground mb-3">{project.type}</p><p className="text-sm text-foreground italic">"{project.review}"</p></CardContent></Card>)}</div></div></section>
      <section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-12 items-center"><div><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">Why Darwin Homeowners Choose Us</h2><div className="space-y-4"><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Local Darwin Experts</h3><p className="text-muted-foreground text-sm">Local contractors understand Darwin's unique weather, council requirements, and local styles</p></div></div><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Fast Response Times</h3><p className="text-muted-foreground text-sm">Same-day quotes and flexible scheduling to suit your Darwin lifestyle</p></div></div><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Quality</h3><p className="text-muted-foreground text-sm"> Local expert fence contractors on all installations.                                          </p></div></div></div></div><div className="relative"><div className="aspect-[4/3] rounded-2xl overflow-hidden shadow-elegant bg-muted"></div></div></div></div></section>
      <section className="py-20 bg-muted/30"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><div className="accent-gradient rounded-2xl p-12 shadow-elegant"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Get Your Darwin Fence Installed?</h2><p className="text-white/90 text-lg mb-8 max-w-2xl mx-auto">Join happy Darwin homeowners. Get your free quotes in 60 seconds.</p><Button variant="secondary" size="lg" onClick={handleQuoteClick}>Get Free Darwin Quotes</Button></div></div></section>
      <Footer />
    </div>;
};
export default Darwin;
