import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FileText } from "lucide-react";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";

const QUOTE_URL = "https://app.quotemyfence.com.au/#/step/1";
const TermsOfService = () => {
  useDocumentTitle("Terms of Service — QuoteMyFence");
  const handleQuoteClick = () => { window.location.href = QUOTE_URL; };
  return <div className="min-h-screen bg-background">
      <Header onQuoteClick={handleQuoteClick} />
      <section className="pt-32 pb-12 bg-gradient-to-br from-primary/5 via-background to-accent/5">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent/10 text-accent mb-6"><FileText className="w-4 h-4" /><span className="text-sm font-medium">Legal Information</span></div>
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">Terms of Use (Job Poster Terms & Website Terms)</h1>
          <p className="text-muted-foreground">Last updated: 25/12/2025</p>
        </div>
      </section>
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-8">
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">1. Introduction</h2><p className="text-muted-foreground mb-4">Welcome to QuoteMyFence. These Terms of Use apply when you access or use our website and platform to find fencing contractors. By using our website and platform, you agree to these Terms.</p><p className="text-muted-foreground mb-4">QuoteMyFence is operated in Australia and provides an online platform that connects property owners ("Users") with fencing contractors ("Contractors").</p><p className="text-muted-foreground">QuoteMyFence does not provide fencing services and is not a party to any contract between Users and Contractors.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">2. Our Service</h2><p className="text-muted-foreground mb-4">QuoteMyFence:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>collects information from Users about their fencing needs;</li><li>shares this information with selected Contractors; and</li><li>provides Users with details of up to three Contractors who may contact them directly.</li></ul><p className="text-muted-foreground mb-4">We simply connect Users and Contractors.</p><p className="text-muted-foreground mb-4">We are not:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>an employer of Contractors;</li><li>an agent of Contractors;</li><li>responsible for any work performed;</li><li>a provider of quotes, pricing, or advice.</li></ul><p className="text-muted-foreground">All arrangements, negotiations, quotes, charges and contracts are exclusively between the User and the Contractor.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">3. No Guarantee of Contractor Availability</h2><p className="text-muted-foreground mb-4">We do not guarantee that:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>you will receive 3 Contractors;</li><li>any Contractor will contact you;</li><li>any Contractor will be suitable for your needs;</li><li>any Contractor will agree to perform your job.</li></ul><p className="text-muted-foreground mb-4">Some locations may have limited Contractor availability.</p><p className="text-muted-foreground">We are not responsible if no Contractor responds or accepts your job.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">4. Contractor Information & Accuracy Disclaimer</h2><p className="text-muted-foreground mb-4">Contractor information shown on QuoteMyFence may include:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>business names;</li><li>number of reviews (as provided by the Contractor);</li><li>number of star ratings (as provided by the Contractor);</li><li>business descriptions;</li><li>services offered;</li><li>contact details.</li></ul><p className="text-muted-foreground mb-4">We do not verify:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>licences (except during initial onboarding);</li><li>insurance;</li><li>identity;</li><li>experience;</li><li>skills;</li><li>qualifications;</li><li>customer reviews or testimonials;</li><li>star ratings;</li><li>compliance with laws.</li></ul><p className="text-muted-foreground">QuoteMyFence is not liable for any errors, omissions, misrepresentations, or false information provided by Contractors.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">5. No Endorsement</h2><p className="text-muted-foreground mb-4">We do not endorse or recommend any particular Contractor.</p><p className="text-muted-foreground">Users choose Contractors entirely at their own risk.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">6. User Responsibilities</h2><p className="text-muted-foreground mb-4">By using QuoteMyFence, Users agree to:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>provide accurate job details;</li><li>allow their personal information to be passed to Contractors;</li><li>conduct independent checks on each Contractor;</li><li>enter into any service contract at their own risk;</li><li>resolve any disputes directly with the Contractor.</li></ul></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">7. Contractors Contact Users Directly</h2><p className="text-muted-foreground mb-4">When a User submits a job request:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>we share the User's details with selected Contractors;</li><li>Contractors may contact Users directly through phone, email, SMS or other means;</li><li>QuoteMyFence is not responsible for any contact, communication, conduct, or outcomes.</li></ul></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">8. Payments</h2><p className="text-muted-foreground mb-4">QuoteMyFence:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>does not charge Users;</li><li>does not accept payments from Users;</li><li>does not handle any Contractor payments;</li><li>is not involved in deposit rules, invoicing, pricing, or job guarantees.</li></ul><p className="text-muted-foreground">Users handle all payments privately with Contractors.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">9. Third-Party Services & Marketing</h2><p className="text-muted-foreground mb-4">QuoteMyFence uses third-party services including but not limited to:</p><ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4"><li>hosting providers</li><li>CRM tools</li><li>Google Analytics and marketing tools</li><li>cloud storage (Firebase)</li><li>email and communication services</li></ul></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">10. No Mediation or Dispute Resolution</h2><p className="text-muted-foreground mb-4">QuoteMyFence does not mediate disputes between Users and Contractors.</p><p className="text-muted-foreground">All disputes must be handled directly between the User and Contractor.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">11. Limitation of Liability</h2><p className="text-muted-foreground mb-4">To the maximum extent permitted under Australian law, QuoteMyFence is not liable for any loss, damage or injury resulting from interactions between Users and Contractors.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">12. Indemnity</h2><p className="text-muted-foreground">Users agree to indemnify and hold QuoteMyFence harmless from any claims, losses, damages, liabilities, costs, or legal fees arising from interactions with Contractors, reliance on Contractor information, misuse of our website, or breach of these Terms.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">13. Intellectual Property</h2><p className="text-muted-foreground">QuoteMyFence owns all website content, branding, logos, layout and design, software and underlying code.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">14. Account Suspension & Access Restrictions</h2><p className="text-muted-foreground">We may suspend or restrict access to the platform if required for system maintenance, security, breach of Terms, or if the platform is shut down or modified.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">15. Changes to These Terms</h2><p className="text-muted-foreground mb-4">We may update these Terms from time to time.</p><p className="text-muted-foreground">Continued use of the website or platform means acceptance of the updated Terms.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">16. Governing Law</h2><p className="text-muted-foreground mb-4">These Terms are governed by the laws of Australia.</p><p className="text-muted-foreground">Any disputes must be handled in the courts of the state or territory where QuoteMyFence operates.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">17. Entire Agreement</h2><p className="text-muted-foreground">These Terms constitute the entire agreement between the User and QuoteMyFence and replace any previous discussions, representations or agreements.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">18. Disclaimer</h2><p className="text-muted-foreground mb-4">QuoteMyFence provides an online information and referral platform only. Nothing on this website constitutes professional, legal, technical, construction, engineering, safety, pricing, regulatory or financial advice.</p><p className="text-muted-foreground">Use of this website and reliance on any information is entirely at your own risk.</p></div>
            <div className="bg-card border border-border rounded-xl p-8"><h2 className="text-2xl font-bold text-foreground mb-4">19. Contact Information</h2><p className="text-muted-foreground">For questions about these Terms, please contact us at:</p><div className="mt-4 text-muted-foreground"><p>Email: info@quotemyfence.com.au</p><p>Phone: 0481 752 344</p></div></div>
          </div>
        </div>
      </section>
      <Footer />
    </div>;
};
export default TermsOfService;
